### ISSUE TITLE
SNMP should return the path of the newly created SNMP manager

### ISSUE THREAD

**Issue by gtmills** [openbmc/phosphor-snmp#1]
```
curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST -d '{"data": ["9.41.167.159", 161] }' \
 https://${bmc}/xyz/openbmc_project/network/snmp/manager/action/Client
{
  "data": null, 
  "message": "200 OK", 
  "status": "ok"
}
```
Otherwise there is no way to know the path /xyz/openbmc_project/network/snmp/manager/d27eeb4.

**Comment by gtmills** [comment]
Without this, the GUI must make an enumerate call after adding an SNMP manager to get the SNMP manager path.

**Comment by gtmills** [comment]
Similiar to https://github.com/openbmc/openbmc/issues/3227

**Comment by ratagupt** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-snmp/+/12517/
